### ISSUE TITLE
Are there all Chinese？

### ISSUE THREAD

**Issue by JaymzZh** [CodeComb/Home#1]
What's this organization? All Chinese?

**Comment by yukozh** [comment]
This organization contains many people who come from all over the world, besides, there are still some Chinese in it. This is an open source organization which contribute on ASP.Net 5, and released some packages to NuGet.org and MyGet.org. If you are interested in it, you can make a contact with me(QQ: 911574351) or leave your QQ number.

**Comment by JaymzZh** [comment]
I can't find you in QQ, my QQ number is 564331480. thanks

**Comment by yukozh** [comment]
Added.
